packages:
  - apps/*
  - features/*/*
  - libs/*
  - libs/sync/*
  - tools/*

allowBuilds:
  nx: true
  '@swc/core': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@op-engineering/op-sqlite@18.2.5'

overrides:
  smol-toml: 1.8.0
  '@op-engineering/op-sqlite': 18.2.5
