/**
 * Attributes a minified JS bundle to packages through its source map, so a
 * bundle-size change can be explained, not only measured. Each run of
 * generated bytes belongs to the source of the mapping segment that starts
 * it; a source path maps to its npm package or workspace project.
 *
 * The shipped artefact is Hermes bytecode (`.hbc`). Its size is what the
 * budget gates; this breakdown is of the minified JS it is compiled from,
 * which is the proportion that explains it.
 */

const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
const DIGIT = new Map([...BASE64].map((char, index) => [char, index]))

/** Decode one base64 VLQ segment into its signed integers. */
export const decodeVlq = (segment: string): number[] => {
  const values: number[] = []
  let value = 0
  let shift = 0
  for (const char of segment) {
    const digit = DIGIT.get(char)
    if (digit === undefined) throw new Error(`invalid VLQ character ${char}`)
    value += (digit & 31) << shift
    if (digit & 32) {
      shift += 5
      continue
    }
    values.push(value & 1 ? -(value >>> 1) : value >>> 1)
    value = 0
    shift = 0
  }
  return values
}

type BasicMap = {
  readonly sources: ReadonlyArray<string>
  readonly mappings: string
}

/** A basic source map, or an indexed one (`sections`), as Metro emits. */
export type SourceMap =
  | BasicMap
  | {
      readonly sections: ReadonlyArray<{
        readonly offset: { readonly line: number; readonly column: number }
        readonly map: BasicMap
      }>
    }

type Start = { readonly line: number; readonly column: number; readonly source: string }

const segmentStarts = (map: BasicMap, offset: { line: number; column: number }): Start[] => {
  const starts: Start[] = []
  let sourceIndex = 0
  const lines = map.mappings.split(';')
  for (let line = 0; line < lines.length; line++) {
    let column = 0
    for (const segment of (lines[line] ?? '').split(',').filter(Boolean)) {
      const fields = decodeVlq(segment)
      column += fields[0] ?? 0
      let source = '(unmapped)'
      if (fields.length >= 4) {
        sourceIndex += fields[1] ?? 0
        source = map.sources[sourceIndex] ?? '(unknown)'
      }
      starts.push({
        line: offset.line + line,
        column: line === 0 ? offset.column + column : column,
        source,
      })
    }
  }
  return starts
}

/**
 * Bytes of generated code per source file. A run of bytes belongs to the
 * segment that starts it; bytes before the first segment count as
 * `(unmapped)`. Columns are UTF-16 units, which equal bytes for the ASCII a
 * minifier emits.
 */
export const bytesPerSource = (code: string, map: SourceMap): Map<string, number> => {
  const starts =
    'sections' in map
      ? map.sections.flatMap((section) => segmentStarts(section.map, section.offset))
      : segmentStarts(map, { line: 0, column: 0 })
  const lineStart: number[] = [0]
  for (let index = 0; index < code.length; index++) {
    if (code.charCodeAt(index) === 10) lineStart.push(index + 1)
  }
  const position = (start: Start) => (lineStart[start.line] ?? code.length) + start.column
  const ordered = starts
    .map((start) => ({ at: position(start), source: start.source }))
    .sort((left, right) => left.at - right.at)
  const totals = new Map<string, number>()
  const add = (source: string, bytes: number) => {
    if (bytes > 0) totals.set(source, (totals.get(source) ?? 0) + bytes)
  }
  add('(unmapped)', ordered[0]?.at ?? code.length)
  for (let index = 0; index < ordered.length; index++) {
    const current = ordered[index]
    if (!current) continue
    const next = ordered[index + 1]?.at ?? code.length
    add(current.source, next - current.at)
  }
  return totals
}

/**
 * The package a source path belongs to: the npm package name under
 * `node_modules` (pnpm layout included), `@viviefs/<path>` for workspace
 * code, else the path's first segment.
 */
export const packageOf = (source: string): string => {
  const normalized = source.replace(/\\/g, '/')
  const nodeModules = normalized.lastIndexOf('node_modules/')
  if (nodeModules >= 0) {
    const rest = normalized.slice(nodeModules + 'node_modules/'.length).split('/')
    return rest[0]?.startsWith('@') ? `${rest[0]}/${rest[1] ?? ''}` : (rest[0] ?? source)
  }
  const workspace = normalized.match(/(?:^|\/)(apps|libs|features|tools)\/([^/]+)(?:\/([^/]+))?/)
  if (workspace) {
    const [, kind, first, second] = workspace
    if (kind === 'features' || (kind === 'libs' && first === 'sync')) {
      return `workspace:${kind}/${first}/${second ?? ''}`
    }
    return `workspace:${kind}/${first}`
  }
  if (source.startsWith('(')) return source
  return normalized.split('/')[0] ?? source
}

export type PackageShare = { readonly name: string; readonly bytes: number }

export const bytesPerPackage = (
  perSource: ReadonlyMap<string, number>,
): ReadonlyArray<PackageShare> => {
  const totals = new Map<string, number>()
  for (const [source, bytes] of perSource) {
    const name = packageOf(source)
    totals.set(name, (totals.get(name) ?? 0) + bytes)
  }
  return [...totals]
    .map(([name, bytes]) => ({ name, bytes }))
    .sort((left, right) => right.bytes - left.bytes)
}
