/**
 * The registry (D76): every production file, its file treatment and why.
 * Filesystem rules only discover files; this list assigns treatments, and a
 * human reviews every change to it. `ownership` fails on a production file
 * without an entry, an entry without a file, a duplicate, an empty rationale,
 * or a shape its treatment does not allow. Changing an entry changes the
 * registry digest the evidence lockfile records.
 */
import type { SuiteId } from '@viviefs/testing'
import type { CoverageProducer } from '@viviefs/testing/vitest'
import type { RegistryEntry } from './file-treatments.ts'

const unit = (path: string, rationale: string, suites?: ReadonlyArray<SuiteId>): RegistryEntry => ({
  path,
  treatment: 'node-unit',
  rationale,
  ...(suites ? { suites } : {}),
})

const integration = (
  path: string,
  rationale: string,
  suites?: ReadonlyArray<SuiteId>,
): RegistryEntry => ({
  path,
  treatment: 'node-integration',
  rationale,
  ...(suites ? { suites } : {}),
})

const support = (path: string, producer: CoverageProducer, rationale: string): RegistryEntry => ({
  path,
  treatment: 'test-support',
  producer,
  rationale,
})

const device = (path: string, gate: `P${number}`, rationale: string): RegistryEntry => ({
  path,
  treatment: 'device',
  gate,
  rationale,
})

const qualifyOnly = (path: string, gate: `P${number}`, rationale: string): RegistryEntry => ({
  path,
  treatment: 'qualify-only',
  gate,
  rationale,
})

const reExport = (path: string, rationale: string): RegistryEntry => ({
  path,
  treatment: 're-export',
  rationale,
})

const byStep = (path: string, step: string, rationale: string): RegistryEntry => ({
  path,
  treatment: 'process-entry',
  runBy: { step },
  rationale,
})

const byTest = (path: string, test: string, rationale: string): RegistryEntry => ({
  path,
  treatment: 'process-entry',
  runBy: { test },
  rationale,
})

const build = (path: string, step: 'docs' | 'build' | 'bundle-size', rationale: string): RegistryEntry => ({
  path,
  treatment: 'build-step',
  step,
  rationale,
})

const slot = (path: string, rationale: string): RegistryEntry => ({
  path,
  treatment: 'named-slot',
  rationale,
})

const types = (path: string, rationale: string): RegistryEntry => ({
  path,
  treatment: 'type-only',
  rationale,
})

const APP = 'apps/evidence-mobile/src'
const PROBES = 'tools/qualification/src/probes'

export const REGISTRY: ReadonlyArray<RegistryEntry> = [
  // apps/docs: the site's pure helpers are unit-tested; Astro loads the rest.
  build('apps/docs/astro.config.ts', 'docs', 'Astro reads the site config; the docs build fails when it is wrong.'),
  build('apps/docs/src/content.config.ts', 'docs', 'Astro entry that registers the collections; checked by the site build, not by tsc.'),
  unit('apps/docs/src/lib/regions.ts', 'Region extraction for embedded samples is pure string logic with unit tests.'),
  build('apps/docs/src/lib/repo-docs-loader.ts', 'docs', 'An Astro content loader: its contract is what the build renders, and the build fails on a missing page.'),
  unit('apps/docs/src/lib/repo-links.ts', 'Link rewriting is pure path logic with unit tests.'),
  unit('apps/docs/src/lib/repo-pages.ts', 'Sidebar groups and ADR status come from pure functions with unit tests.'),
  unit('apps/docs/src/lib/repo.ts', 'Which repository files become which site pages is pure path logic with unit tests.'),
  build('apps/docs/src/pages/research/[record].html.ts', 'docs', 'An Astro endpoint that serves research HTML as is; exercised by the docs build.'),

  // apps/evidence-mobile: the evidence app runs only on a device or in a browser (D70).
  device('apps/evidence-mobile/index.ts', 'P01', 'Expo entry: registers the root component with the native runtime.'),
  build('apps/evidence-mobile/babel.config.js', 'bundle-size', 'Metro loads it to transform every module; the Hermes bundle build fails without it.'),
  build('apps/evidence-mobile/metro.config.js', 'bundle-size', 'Metro resolver and transformer config; exercised by the Hermes bundle build.'),
  build('apps/evidence-mobile/plugins/with-third-party-sqlite.js', 'bundle-size', 'Expo config plugin for the iOS Podfile; read when the app config is evaluated for the bundle.'),
  device(`${APP}/app.tsx`, 'P01', 'Chooses the gate screen at launch; React Native only.'),
  device(`${APP}/crypto-setup.ts`, 'P01', 'Installs the Hermes crypto polyfill before anything else runs.'),
  types(`${APP}/env.d.ts`, 'Declares the Expo environment variables the app reads.'),
  reExport(`${APP}/index.ts`, 'The package entry re-exports the app.'),
  device(`${APP}/intl.android.ts`, 'P01', 'Loads the Intl polyfill on Android Hermes, which cannot drive DateTime zones.'),
  device(`${APP}/intl.ios.ts`, 'P01', 'iOS platform variant: Hermes on iOS needs no Intl polyfill, so the module is empty on purpose.'),
  device(`${APP}/intl.ts`, 'P01', 'Web and default platform variant: Intl is native there, so the module is empty on purpose.'),
  device(`${APP}/p01-app.tsx`, 'P01', 'P01 screen: shows the Effect checks running on the device.'),
  device(`${APP}/p01-effect-checks.ts`, 'P01', 'P01 checks that Effect runs on Hermes; only meaningful on the device runtime.'),
  device(`${APP}/p01-runtime.ts`, 'P01', 'P01 device runtime that publishes results for the probe.'),
  device(`${APP}/p01-sql-import.ts`, 'P01', 'Imports the SQL modules on Hermes to prove the Migrator workaround.'),
  device(`${APP}/p02-app.tsx`, 'P02', 'P02 screen for the SQLite driver checks.'),
  device(`${APP}/p02-expo-sqlite.ts`, 'P02', 'The expo-sqlite fallback driver, exercised on device.'),
  device(`${APP}/p02-official.ts`, 'P02', 'Native variant of the official SQLite driver for P02.'),
  device(`${APP}/p02-official.web.ts`, 'P02', 'Web variant of the official SQLite driver for P02 (OPFS).'),
  device(`${APP}/p02-opfs-import-meta.ts`, 'P02', 'Redirects wa-sqlite wasm fetches under Expo web; browser only.'),
  device(`${APP}/p02-opfs-worker.ts`, 'P02', 'OPFS worker body for P02; runs in a browser worker.'),
  device(`${APP}/p02-runtime.ts`, 'P02', 'P02 device runtime that publishes driver results.'),
  device(`${APP}/p02-sql-checks.ts`, 'P02', 'The SQL checks P02 runs against each driver on the device.'),
  device(`${APP}/p03-app.tsx`, 'P03', 'P03 screen for OTLP export from Hermes.'),
  device(`${APP}/p03-runtime.ts`, 'P03', 'P03 device runtime: exports spans to motel from the device.'),
  device(`${APP}/p04-app.tsx`, 'P04', 'P04 screen: log-store/conformance on the native and web stores.'),
  device(`${APP}/p04-official.ts`, 'P04', 'Native store layer for P04 on the device.'),
  device(`${APP}/p04-official.web.ts`, 'P04', 'Web store layer for P04 (OPFS).'),
  device(`${APP}/p04-opfs-worker.ts`, 'P04', 'OPFS worker body for P04; runs in a browser worker.'),
  device(`${APP}/p04-runtime.ts`, 'P04', 'Runs log-store/conformance on the device store.'),
  device(`${APP}/p05-app.tsx`, 'P05', 'P05 screen: changesets/conformance on the native and web stores.'),
  device(`${APP}/p05-official.ts`, 'P05', 'Native store layer for P05 on the device.'),
  device(`${APP}/p05-official.web.ts`, 'P05', 'Web store layer for P05 (OPFS).'),
  device(`${APP}/p05-opfs-worker.ts`, 'P05', 'OPFS worker body for P05; runs in a browser worker.'),
  device(`${APP}/p05-runtime.ts`, 'P05', 'Runs changesets/conformance on the device store.'),
  device(`${APP}/p07-app.tsx`, 'P07', 'P07 screen for device resume after a force-quit.'),
  device(`${APP}/p07-official.ts`, 'P07', 'Native store layer for P07 on the device.'),
  device(`${APP}/p07-runtime.ts`, 'P07', 'P07 device runtime: the engine, wake scheduler and launch sweep on Hermes.'),
  device(`${APP}/p11-app.tsx`, 'P11', 'P11 screen: sign-in, sync and replica switching on the device.'),
  device(`${APP}/p11-control.ts`, 'P11', 'P11 device positive controls selected by environment variable.'),
  device(`${APP}/p11-opfs-worker.ts`, 'P11', 'OPFS worker body for P11 on web.'),
  device(`${APP}/p11-platform.ts`, 'P11', 'Native sign-in ports for P11.'),
  device(`${APP}/p11-platform.web.ts`, 'P11', 'Web sign-in ports for P11.'),
  device(`${APP}/p11-runtime.ts`, 'P11', 'P11 device runtime: sign-in session, sync client and local replica.'),
  device(`${APP}/probe-report.ts`, 'P01', 'Posts device results to the probe report server; needs the device runtime.'),

  // apps/evidence-server: composed and proven over HTTP.
  reExport('apps/evidence-server/src/index.ts', 'The package entry re-exports the server composition.'),
  qualifyOnly('apps/evidence-server/src/main.ts', 'P11', 'Reads VIVIEFS_* and serves over HTTP; the P11 lab starts it as a process.'),
  integration('apps/evidence-server/src/server.ts', 'The HTTP composition needs a real server and store; its integration test drives it over HTTP.'),

  // features/evidence: the exemplar slice.
  unit('features/evidence/client/src/index.ts', 'Public entry with the P08 variant table; imported by unit tests.'),
  {
    path: 'features/evidence/client/src/intent-composer/IntentComposerScreen.tsx',
    treatment: 'rendered-ui',
    stories: 'features/evidence/client/src/intent-composer/IntentComposerScreen.stories.test.tsx',
    rationale: 'A rendered screen: its stories run with play and axe (jsdom until P12).',
  },
  {
    path: 'features/evidence/client/src/intent-composer/IntentComposerView.tsx',
    treatment: 'rendered-ui',
    stories: 'features/evidence/client/src/intent-composer/IntentComposerScreen.stories.test.tsx',
    rationale: 'The pure view the screen renders; exercised through the screen stories.',
  },
  unit('features/evidence/client/src/intent-composer/atom.ts', 'Retained P08 variant on Effect with Atom; the composer suite runs against it.', ['interaction-state/intent-composer']),
  support('features/evidence/client/src/intent-composer/broken.ts', 'unit', 'Positive control: a composer that cannot finish, so the suite must fail on it.'),
  support('features/evidence/client/src/intent-composer/checks.ts', 'unit', 'The interaction-state/intent-composer suite itself.'),
  unit('features/evidence/client/src/intent-composer/driver.ts', 'The driver contract every composer variant implements; used by the suite in unit.'),
  unit('features/evidence/client/src/intent-composer/effect-machine.ts', 'The chosen IntentComposer (ADR-0020); the composer suite runs against it.', ['interaction-state/intent-composer']),
  unit('features/evidence/client/src/intent-composer/graph.ts', 'One graph for the machine and its diagram; pure, with unit tests.'),
  unit('features/evidence/client/src/intent-composer/interaction.ts', 'The ephemeral interaction state types and transitions; pure.'),
  unit('features/evidence/client/src/intent-composer/query-atom.ts', 'The query atom the screen reads; unit-tested.'),
  unit('features/evidence/client/src/intent-composer/screen-view.ts', 'The screen-view selector over domain facts (D41); pure, with unit tests.'),
  unit('features/evidence/client/src/intent-composer/xstate.ts', 'Retained P08 variant on XState v5; the composer suite runs against it.', ['interaction-state/intent-composer']),
  unit('features/evidence/model/src/command.ts', 'Shared commands (D36) are pure; the sync suites run them on the client and the server.', ['sync/protocol']),
  unit('features/evidence/model/src/device-resume.ts', 'The device-resume workflow definition; the P09 and P11 worlds import it in unit.'),
  reExport('features/evidence/model/src/index.ts', 'The package entry re-exports the model.'),
  slot('features/evidence/server/src/index.ts', 'Named slot for server-side validators; empty until they exist.'),

  // libs
  unit('libs/blobs/src/index.ts', 'The in-memory content-hash store is pure; the sync suites use it in unit.', ['sync/protocol']),
  slot('libs/crypto-shred/src/index.ts', 'Named slot until P16.'),
  unit('libs/datom/src/account.ts', 'Deterministic account ids; pure, reached by the identity checks in unit.'),
  unit('libs/datom/src/catalog.ts', 'The attribute catalog is data plus lookups; unit tests read it.'),
  unit('libs/datom/src/clock-live.ts', 'The live clock and entropy Layers; unit tests and the sync world run them.'),
  unit('libs/datom/src/clock.ts', 'The HlcClock and entropy ports; pure service definitions.'),
  unit('libs/datom/src/hlc.ts', 'Hybrid logical clock (ADR-0007); pure functions with unit tests.'),
  unit('libs/datom/src/ids.ts', 'Strict-composition ids (D38); pure, with unit tests.'),
  reExport('libs/datom/src/index.ts', 'The package entry re-exports the datom core.'),
  unit('libs/datom/src/keys.ts', 'Prefix and attribute keys for invalidation (D42); pure, with unit tests.'),
  unit('libs/datom/src/log-store.ts', 'The shared LogStore over any SqlClient; the sync suites run it on sqlite-node in unit.', ['sync/protocol']),
  unit('libs/datom/src/manifest.ts', 'Changeset manifests and hashing; pure, with unit tests.'),
  unit('libs/datom/src/migrate.ts', 'Schema migrations for the log tables; run by every store the unit suites open.'),
  unit('libs/datom/src/projector.ts', 'The projector folds datoms into read models; the sync suites project in unit.', ['sync/protocol']),
  unit('libs/datom/src/read-models.ts', 'Read-model queries over the projection; reached by the sync suites in unit.'),
  unit('libs/datom/src/rows.ts', 'Row Schemas and rowsOf (D79); every store query in the unit suites decodes through it.'),
  unit('libs/datom/src/schema.ts', 'The datom Schemas; pure definitions.'),
  support('libs/datom/src/suites/changesets.ts', 'integration', 'The changesets/conformance suite, run by each store.'),
  reExport('libs/datom/src/suites/index.ts', 'The suites entry re-exports the datom suites.'),
  support('libs/datom/src/suites/log-store.ts', 'integration', 'The log-store/conformance suite, run by each store.'),
  unit('libs/datom/src/visibility.ts', 'Visibility rules for drafts and commits; pure, with unit tests.'),
  unit('libs/datom/src/vocabulary.ts', 'Pinned attribute names (D44); unit tests hold them.'),
  unit('libs/identity/src/caller-statement.ts', "The server's statement about the caller; a Schema used by the identity checks."),
  unit('libs/identity/src/caller.ts', 'The Caller service tag; defined when the sync server loads in unit.'),
  reExport('libs/identity/src/index.ts', 'The package entry re-exports the identity pattern.'),
  unit('libs/identity/src/oidc-sign-in-session.ts', 'The OIDC sign-in session, tested in-process against a served fake issuer.'),
  unit('libs/identity/src/oidc.ts', 'The jose token verifier; identity/token-verifier runs against it on a served fake issuer.', ['identity/token-verifier']),
  unit('libs/identity/src/sign-in-session.ts', 'The SignInSession port and its memory vault; pure.'),
  support('libs/identity/src/suites/fake-issuer-server.ts', 'unit', 'Serves the fake issuer over HTTP for the OIDC tests.'),
  support('libs/identity/src/suites/fake-issuer.ts', 'unit', 'The in-process fake identity provider.'),
  reExport('libs/identity/src/suites/index.ts', 'The suites entry re-exports the identity suites.'),
  reExport('libs/identity/src/suites/node.ts', 'The Node-only suites entry re-exports the served fake issuer.'),
  support('libs/identity/src/suites/token-verifier.ts', 'unit', 'The identity/token-verifier suite itself.'),
  unit('libs/identity/src/token-verifier.ts', 'The TokenVerifier port; identity/token-verifier runs against its fake.', ['identity/token-verifier']),
  device('libs/platform-native/src/crypto-polyfill.ts', 'P01', 'Supplies crypto on Hermes, which lacks it; meaningless in Node.'),
  reExport('libs/platform-native/src/index.ts', 'The package entry re-exports the native adapters.'),
  device('libs/platform-native/src/intl-polyfill.ts', 'P01', 'Android Hermes Intl polyfill; loads only under Metro.'),
  device('libs/platform-native/src/notifications.ts', 'P07', 'Local notifications through Expo; needs the native module.'),
  device('libs/platform-native/src/sign-in.ts', 'P11', 'Expo sign-in ports (browser session, secure store); native only.'),
  device('libs/platform-native/src/wake.ts', 'P07', 'Wake adapter over local notifications; native only.'),
  reExport('libs/store-postgres/src/index.ts', 'The package entry re-exports the Postgres store.'),
  integration('libs/store-postgres/src/layer.ts', 'The Postgres store needs PGlite; its integration tests run the log-store suites.', ['log-store/conformance', 'changesets/conformance']),
  reExport('libs/store-sqlite-native/src/index.ts', 'The package entry re-exports the native store.'),
  device('libs/store-sqlite-native/src/layer.ts', 'P04', 'op-sqlite needs the native module; P04 runs log-store/conformance on it on devices.'),
  reExport('libs/store-sqlite-node/src/index.ts', 'The package entry re-exports the node:sqlite store.'),
  integration('libs/store-sqlite-node/src/layer.ts', 'The node:sqlite store; its integration tests run the log-store suites and a migration.', ['log-store/conformance', 'changesets/conformance']),
  reExport('libs/store-sqlite-wasm/src/index.ts', 'The package entry re-exports the web store.'),
  device('libs/store-sqlite-wasm/src/layer.ts', 'P04', 'wa-sqlite over OPFS needs a browser worker; P04 runs the suite on web.'),
  device('libs/store-sqlite-wasm/src/opfs.ts', 'P04', 'The OPFS worker body and database deletion; browser only.'),
  types('libs/store-sqlite-wasm/src/wa-sqlite.d.ts', 'Declares the two wa-sqlite modules opfs.ts loads directly.'),
  unit('libs/sync/client/src/client.ts', 'The sync client; the sync and membership suites drive it in-process.', ['sync/protocol', 'identity/membership']),
  reExport('libs/sync/client/src/index.ts', 'The package entry re-exports the sync client.'),
  unit('libs/sync/client/src/replica.ts', 'Replica naming per provider account; reached by the membership suite.', ['identity/membership']),
  reExport('libs/sync/protocol/src/index.ts', 'The package entry re-exports the sync protocol.'),
  unit('libs/sync/protocol/src/rpc.ts', 'The RPC group and bearer authentication; the sync suites run it.', ['sync/protocol', 'identity/membership']),
  reExport('libs/sync/server/src/index.ts', 'The package entry re-exports the sync server.'),
  unit('libs/sync/server/src/server.ts', 'Server authority; the sync and membership suites drive it in-process.', ['sync/protocol', 'identity/membership']),
  unit('libs/telemetry/src/durable-spans.ts', 'Durable spans from journal facts; pure, with unit tests.'),
  reExport('libs/telemetry/src/index.ts', 'The package entry re-exports telemetry.'),
  unit('libs/telemetry/src/layer.ts', 'The live OTLP layer definition; built in unit, exported only in P03.'),
  support('libs/telemetry/src/suites/projection.ts', 'integration', 'The tracing/projection suite itself.'),
  reExport('libs/telemetry/src/suites/index.ts', 'The suites entry re-exports the telemetry suite.'),
  integration('libs/telemetry/src/trace-projector.ts', 'The trace projector; tracing/projection runs it on sqlite-node and PGlite.', ['tracing/projection']),
  unit('libs/telemetry/src/trace-sink.ts', 'The TraceSink contract and its memory sink; the lab sinks are P10 only.'),
  types('libs/testing/src/check.ts', 'The CheckResult type every suite returns.'),
  reExport('libs/testing/src/index.ts', 'The package entry re-exports the helpers and the catalogue.'),
  reExport('libs/testing/src/node.ts', 'The Node-only entry re-exports the temp-directory helper.'),
  support('libs/testing/src/run-unscoped.ts', 'unit', 'Runs a suite on a fresh runtime so it does not inherit the test Scope.'),
  support('libs/testing/src/suites.ts', 'unit', 'The suite catalogue; its test checks ids, patterns and sources.'),
  support('libs/testing/src/temp-directory.ts', 'unit', 'Scoped temporary directories for store tests.'),
  support('libs/testing/src/vitest.ts', 'unit', 'The one Vitest config shape; its test checks which producer runs which file.'),
  reExport('libs/ui/src/index.ts', 'The package entry re-exports the UI hooks.'),
  unit('libs/ui/src/settled-text.ts', 'A React hook with timers; unit-tested under jsdom until P12 moves UI to Chromium.'),
  integration('libs/workflow-engine/src/config.ts', 'Engine configuration Layer; exercised by the engine suites.', ['durable-workflow/crash-matrix']),
  integration('libs/workflow-engine/src/crash-hook.ts', 'Simulated kills at each boundary; only the crash matrix arms it.', ['durable-workflow/crash-matrix']),
  integration('libs/workflow-engine/src/engine.ts', 'The datom-backed engine; its suites run it on sqlite-node and PGlite with kills.', [
    'durable-workflow/crash-matrix',
    'device-durability/launch-sweep',
    'tracing/engine-trace',
  ]),
  reExport('libs/workflow-engine/src/index.ts', 'The package entry re-exports the engine.'),
  unit('libs/workflow-engine/src/journal.ts', 'Exit values in the journal; pure, with unit tests.'),
  support('libs/workflow-engine/src/suites/crash-matrix.ts', 'integration', 'The durable-workflow/crash-matrix suite and its memory-engine control.'),
  support('libs/workflow-engine/src/suites/exit-replay.ts', 'integration', 'The typed-failure replay check of the crash matrix.'),
  reExport('libs/workflow-engine/src/suites/index.ts', 'The suites entry re-exports the engine suites.'),
  support('libs/workflow-engine/src/suites/lab.ts', 'integration', 'The lab person an engine writes as when no one is signed in.'),
  support('libs/workflow-engine/src/suites/launch-sweep.ts', 'integration', 'The device-durability/launch-sweep suite itself.'),
  support('libs/workflow-engine/src/suites/trace-scenario.ts', 'integration', 'The tracing/engine-trace suite and its crash-and-resume run.'),
  integration('libs/workflow-engine/src/sweep.ts', 'The launch and foreground sweep; device-durability/launch-sweep runs it.', ['device-durability/launch-sweep']),
  unit('libs/workflow-engine/src/trace.ts', 'Entity-keyed span ids (D32); pure, with unit tests.'),
  integration('libs/workflow-engine/src/wake.ts', 'The wake-scheduler port; the launch sweep exercises it.', ['device-durability/launch-sweep']),

  // tools
  slot('tools/generators/src/index.ts', 'Named slot until the exercise generator (D66).'),
  byTest('tools/qualification/src/cli.ts', 'tools/qualification/src/cli.test.ts', 'The qualify CLI (ADR-0030); its characterization tests run it as a process.'),
  unit('tools/qualification/src/gates.ts', 'The gate table; the safety test reads it.'),
  reExport('tools/qualification/src/index.ts', 'The package entry re-exports the gate table.'),
  unit('tools/qualification/src/ledger.ts', 'The ledger; its test runs every scenario in-process against a scratch repository.'),
  unit('tools/qualification/src/process.ts', 'Child-process helpers with timeouts; unit-tested.'),
  unit(`${PROBES}/agent-cli.ts`, 'Wrappers over @expo/agent-cli; the argument building is unit-tested, device calls run in qualify.'),
  unit(`${PROBES}/dev-client.ts`, 'Development-build helpers; the pure parts are unit-tested, device runs happen in qualify.'),
  unit(`${PROBES}/devices.ts`, 'Simulator and emulator helpers; the pure parts are unit-tested, device runs happen in qualify.'),
  qualifyOnly(`${PROBES}/keycloak.ts`, 'P11', 'Starts Keycloak on Apple Container; a lab.'),
  unit(`${PROBES}/motel.ts`, 'motel daemon helpers; the pure parts are unit-tested, the daemon runs in qualify.'),
  qualifyOnly(`${PROBES}/not-yet-run.ts`, 'P12', 'Refuses to pass for a registered gate without a probe.'),
  qualifyOnly(`${PROBES}/p01.ts`, 'P01', 'The P01 runner: builds and drives the evidence app on devices.'),
  qualifyOnly(`${PROBES}/p02.ts`, 'P02', 'The P02 runner: drivers on iOS, Android and web.'),
  qualifyOnly(`${PROBES}/p03.ts`, 'P03', 'The P03 runner: OTLP from devices into motel.'),
  qualifyOnly(`${PROBES}/p04.ts`, 'P04', 'The P04 runner: the log-store suite on host and devices, recorded.'),
  qualifyOnly(`${PROBES}/p05.ts`, 'P05', 'The P05 runner: the changesets suite on host and devices, recorded.'),
  qualifyOnly(`${PROBES}/p06.ts`, 'P06', 'The P06 runner: records the crash matrix the engine runs in verify.'),
  qualifyOnly(`${PROBES}/p07.ts`, 'P07', 'The P07 runner: force-quit and resume on devices.'),
  qualifyOnly(`${PROBES}/p08.ts`, 'P08', 'The P08 runner: records the composer comparison.'),
  support(`${PROBES}/p09-checks.ts`, 'unit', 'The sync/protocol suite itself (moves to libs/sync with the sync guide, D80).'),
  unit(`${PROBES}/p09-spans.ts`, 'Draws the P09 span review; the P09 test compares it with the evidence note.'),
  qualifyOnly(`${PROBES}/p09.ts`, 'P09', 'The P09 runner: records the sync suite.'),
  qualifyOnly(`${PROBES}/p10-checks.ts`, 'P10', 'The tracing/sink suite: needs Jaeger and otel-lgtm, so it runs only in qualify.'),
  unit(`${PROBES}/p10-review.ts`, 'Draws the P10 span tree; the P10 test compares it with the evidence note.'),
  qualifyOnly(`${PROBES}/p10-sinks.ts`, 'P10', 'Starts the P10 telemetry sinks on Apple Container; a lab.'),
  qualifyOnly(`${PROBES}/p10.ts`, 'P10', 'The P10 runner: projection and sinks, recorded.'),
  support(`${PROBES}/p11-checks.ts`, 'unit', 'The identity/membership suite itself (moves with the identity guide, D80).'),
  qualifyOnly(`${PROBES}/p11-device.ts`, 'P11', 'Drives sign-in on the simulator, emulator and web.'),
  qualifyOnly(`${PROBES}/p11-http.ts`, 'P11', "P11 over HTTP with Keycloak's tokens; a lab."),
  qualifyOnly(`${PROBES}/p11-keycloak.ts`, 'P11', 'The token suite against Keycloak; a lab.'),
  qualifyOnly(`${PROBES}/p11-lab.ts`, 'P11', 'Starts Keycloak and the evidence server for device runs.'),
  unit(`${PROBES}/p11-spans.ts`, 'Draws the P11 sequence diagrams; the P11 test compares them with the evidence note.'),
  qualifyOnly(`${PROBES}/p11.ts`, 'P11', 'The P11 runner: every section, recorded.'),
  qualifyOnly(`${PROBES}/p12.ts`, 'P12', 'Registered, not yet run.'),
  qualifyOnly(`${PROBES}/p13.ts`, 'P13', 'Registered, not yet run.'),
  qualifyOnly(`${PROBES}/p14.ts`, 'P14', 'Registered, not yet run.'),
  qualifyOnly(`${PROBES}/p15.ts`, 'P15', 'Registered, not yet run.'),
  qualifyOnly(`${PROBES}/p16.ts`, 'P16', 'Registered, not yet run.'),
  qualifyOnly(`${PROBES}/p17.ts`, 'P17', 'Registered, not yet run.'),
  unit(`${PROBES}/report-server.ts`, 'Receives device results over HTTP; unit-tested with a local server.'),
  unit(`${PROBES}/span-review.ts`, 'The span-review convention: markers, drift and check notes; pure.'),
  support(`${PROBES}/sync-world.ts`, 'unit', 'The authenticated sync world the sync and membership suites run in.'),
  qualifyOnly(`${PROBES}/web-client.ts`, 'P02', 'Drives the web build in a browser for P02, P04, P05 and P11.'),
  unit('tools/verify/src/bundle-report.ts', 'Attributes a bundle to packages through its source map; unit-tested.'),
  unit('tools/verify/src/baseline.ts', 'Compares repeated producer runs and composes the lockfile; pure, with unit tests.'),
  byStep('tools/verify/src/bundle-size.ts', 'bundle-size', 'Builds and measures the Hermes bundles; the bundle-size step runs it.'),
  byStep('tools/verify/src/check-diagrams.ts', 'diagrams', 'Reads every Markdown file and applies diagrams.ts; the diagrams step runs it.'),
  byStep('tools/verify/src/check-evidence.ts', 'evidence', "Loads this run's producer artifacts and applies evidence.ts; the evidence step runs it."),
  byStep('tools/verify/src/check-lint-scope.ts', 'lint-scope', 'Asks ESLint about every file and applies lint-scope.ts; the lint-scope step runs it.'),
  byStep('tools/verify/src/check-ownership.ts', 'ownership', 'Reads the projects and the registry and applies ownership.ts; the ownership step runs it.'),
  byStep('tools/verify/src/check-skills.ts', 'skills', 'Reads the skill tree and applies skills-tree.ts; the skills step runs it.'),
  unit('tools/verify/src/diagrams.ts', 'The Mermaid edge rule; pure, with failing cases in unit tests.'),
  unit('tools/verify/src/docs-only.ts', 'The docs-only path rule; pure, with unit tests.'),
  unit('tools/verify/src/evidence-artifacts.ts', "Reads the producers' artifacts and the lockfile under a given root; tested on a scratch directory."),
  unit('tools/verify/src/evidence.ts', 'The evidence verdicts over injected runs and lockfile; pure, with unit tests.'),
  unit('tools/verify/src/evidence-registry.ts', 'This registry; the ownership tests read it.'),
  unit('tools/verify/src/file-treatments.ts', 'File treatments and their shape checks; pure, with unit tests.'),
  reExport('tools/verify/src/index.ts', 'The package entry re-exports the stage table.'),
  unit('tools/verify/src/lint-scope.ts', 'The lint-scope rule over injected files; pure, with unit tests.'),
  unit('tools/verify/src/lockfile.ts', 'Coverage tuples, the registry digest and stable JSON; pure, with unit tests.'),
  unit('tools/verify/src/ownership.ts', 'Project tags and registry validation over injected data; pure, with unit tests.'),
  unit('tools/verify/src/producers.ts', 'Which projects and files each coverage producer takes, from project.json and the registry; unit-tested.'),
  unit('tools/verify/src/skills-tree.ts', 'The skill-tree rule; pure, with unit tests.'),
  unit('tools/verify/src/stages.ts', 'The stage table and selectors; unit-tested.'),
  byTest('tools/verify/src/verify.ts', 'tools/verify/src/cli.test.ts', 'The verify CLI (ADR-0030); its characterization tests run it as a process.'),
]
